title: Gamma dashboard
logo: /assets/img/gamma.png
#description: text below image
show_downloads: true
#remote_theme: pages-themes/hacker@v0.2.0
#remote_theme: "Paramdigma/hydryne-jekyll-theme"
#remote_theme: andrewbanchich/forty-jekyll-theme
#remote_theme: jeromelachaud/freelancer-theme
#remote_theme: dieghernan/chulapa
#remote_theme: daattali/beautiful-jekyll
remote_theme: stevenmichiels/beautiful-jekyll
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

navbar-links:
  Home: ""
  Projects: "projects"
  About Me: "aboutme"
  Presentations: "presentations"
  PPM: "ppm"

  author:
  name: Steven Michiels
  email: "steven.michiels2@gmail.com"
  github: stevenmichiels
  twitter: Ursus2021